export default {
    9: {
        title: 'Natural Gas',
        subtitle: 'Natural Gas Subsection',
        category: 9,
        icon: require('../images/building_code.png'),
        background: require('../images/Sunrise-Engineering-Experience-Natural-Gas-Pipeline-Design-Service-150x150.jpg'),
        config_icon: require('../images/natural_gas_icon.png'),
        config_background: require('../images/Sunrise-Engineering-Experience-Natural-Gas-Pipeline-Design-Service-150x150.jpg'),
    },
    11: {
        title: 'Engineering',
        subtitle: 'Engineering Subsection',
        category: 11,
        icon: require('../images/engineering.png'),
        background: require('../images/sunrise-engineering-services-experience-engineering-150x150.jpg'),
        config_icon: require('../images/engineering_icon.png'),
        config_background: require('../images/sunrise-engineering-services-experience-engineering-150x150.jpg'),
    },
    12: {
        title: 'Survey',
        subtitle: 'Survey Subsection',
        category: 12,
        icon: require('../images/survey.png'),
        background: require('../images/head_background.png'),
        config_icon: require('../images/survey_icon.png'),
        config_background: require('../images/head_background.png'),
    },
    13: {
        title: 'Cloud Smart',
        subtitle: 'Cloud Smart Subsection',
        category: 13,
        icon: require('../images/cloud_smart.png'),
        background: require('../images/sunrise-engineering-services-experience-gis-150x150.jpg'),
        config_icon: require('../images/cloud_smart_icon.png'),
        config_background: require('../images/sunrise-engineering-services-experience-gis-150x150.jpg'),
    },
    14: {
        title: 'Building Code',
        subtitle: 'Building Code Subsection',
        category: 14,
        icon: require('../images/building_code.png'),
        background: require('../images/sunrise-engineering-services-experience-building-code-services-150x150.jpg'),
        config_icon: require('../images/building_code_icon.png'),
        config_background: require('../images/sunrise-engineering-services-experience-building-code-services-150x150.jpg'),
    },
    firmstats: {
        title: 'Firm Stats',
        subtitle: 'Firm Stats Subsection',
        category: false,
        icon: require('../images/firm_stats_icon.png'),
        background: require('../images/firmstats_background.png'),
        config_icon: require('../images/firm_stats_icon.png'),
        config_background: require('../images/firmstats_background.png'),
    },
};
